/** 列表的模拟数据 */
export const TableDemoData = [
  {
    id: 1,
    username: '张三',
    score: 85,
    gender: '1',
    age: 22,
    hobby: ['1', '2'],
    skill: ['3'],
    birthday: '1999-01-01',
  },
  {
    id: 2,
    username: '李四',
    score: 75,
    gender: '2',
    age: 25,
    hobby: ['2'],
    skill: ['1'],
    birthday: '1998-02-02',
  },
  {
    id: 3,
    username: '王五',
    score: 92,
    gender: '1',
    age: 21,
    hobby: ['3'],
    skill: ['2'],
    birthday: '2000-03-03',
  },
  {
    id: 4,
    username: '赵六',
    score: 68,
    gender: '2',
    age: 23,
    hobby: ['1'],
    skill: ['3'],
    birthday: '1997-04-04',
  },
  {
    id: 5,
    username: '孙七',
    score: 88,
    gender: '1',
    age: 24,
    hobby: ['2', '3'],
    skill: ['1', '2'],
    birthday: '1996-05-05',
  },
  {
    id: 6,
    username: '周八',
    score: 72,
    gender: '2',
    age: 26,
    hobby: ['1', '2'],
    skill: ['1', '3'],
    birthday: '1995-06-06',
  },
  {
    id: 7,
    username: '吴九',
    score: 95,
    gender: '1',
    age: 20,
    hobby: ['3'],
    skill: ['2'],
    birthday: '2001-07-07',
  },
  {
    id: 8,
    username: '郑十',
    score: 65,
    gender: '2',
    age: 27,
    hobby: ['1'],
    skill: ['3'],
    birthday: '1994-08-08',
  },
  {
    id: 9,
    username: '钱十一',
    score: 81,
    gender: '1',
    age: 22,
    hobby: ['2'],
    skill: ['1'],
    birthday: '1999-09-09',
  },
  {
    id: 10,
    username: '孙十二',
    score: 78,
    gender: '2',
    age: 23,
    hobby: ['3'],
    skill: ['2'],
    birthday: '1998-10-10',
  },
  {
    id: 11,
    username: '李十三',
    score: 90,
    gender: '1',
    age: 21,
    hobby: ['1'],
    skill: ['3'],
    birthday: '2000-11-11',
  },
  {
    id: 12,
    username: '赵十四',
    score: 60,
    gender: '2',
    age: 24,
    hobby: ['2', '3'],
    skill: ['1', '2'],
    birthday: '1997-12-12',
  },
];

/** 字典的模拟数据 */
export const DemoDicts = {
  gender: [
    { label: '男', value: '1' },
    { label: '女', value: '2' },
  ],
  hobby: [
    { label: '篮球', value: '1' },
    { label: '足球', value: '2' },
    { label: '游泳', value: '3' },
  ],
  skill: [
    { label: '编程', value: '1' },
    { label: '绘画', value: '2' },
    { label: '音乐', value: '3' },
  ],
};
